# Generated by Django 4.1.7 on 2023-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0002_infantry_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='infantry',
            name='equipment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='infantry',
            name='weapon_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
