# Generated by Django 4.1.7 on 2023-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0003_infantry_equipment_infantry_weapon_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='effects',
            field=models.TextField(blank=True, default=''),
        ),
    ]
