# Generated by Django 4.1.7 on 2023-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0005_infantry_member_cost_infantry_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='infantry',
            name='force_org',
            field=models.CharField(default='Troops', max_length=50),
        ),
    ]
