# Generated by Django 4.1.7 on 2023-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0006_infantry_force_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infantry',
            options={'ordering': ['force_org']},
        ),
        migrations.AddField(
            model_name='infantry',
            name='inv_save',
            field=models.IntegerField(default=0),
        ),
    ]
