# Generated by Django 4.1.7 on 2023-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0008_infantry_squad_max_infantry_squad_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infantry',
            name='squad_max',
        ),
        migrations.AddField(
            model_name='infantry',
            name='squad_add',
            field=models.IntegerField(default=0),
        ),
    ]
