# Generated by Django 4.1.7 on 2023-04-25 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import heresy.models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0010_infantry_squad_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='infantry',
            name='force_org',
            field=models.CharField(default='Troops', max_length=50, validators=[heresy.models.validate_force_org]),
        ),
        migrations.CreateModel(
            name='ListBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_org', models.CharField(max_length=50, validators=[heresy.models.validate_force_org])),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_points', models.IntegerField(default=0)),
                ('unit_weapons', models.TextField(blank=True, default='')),
                ('armylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heresy.armylists')),
            ],
        ),
    ]
