# Generated by Django 4.1.7 on 2023-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0011_armylists_alter_infantry_force_org_listblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='listblocks',
            name='unit_members',
            field=models.IntegerField(default=1),
        ),
    ]
