# Generated by Django 4.1.7 on 2023-05-01 16:35

from django.db import migrations, models
import heresy.models


class Migration(migrations.Migration):

    dependencies = [
        ('heresy', '0012_listblocks_unit_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armylists',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='weapons',
            name='name',
            field=models.CharField(max_length=50, validators=[heresy.models.validate_weapon_name]),
        ),
    ]
