# Generated by Django 4.1.7 on 2023-03-16 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_listings_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='item_image',
            field=models.URLField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
