# Generated by Django 4.1.7 on 2023-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_item_image_alter_listings_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
