# Generated by Django 4.1.7 on 2023-03-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
