# Generated by Django 4.1.7 on 2023-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
