# Generated by Django 4.1.7 on 2023-03-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='comments',
            name='commenter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
