# Generated by Django 4.1.7 on 2023-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_artifact_set_characters_artifact_user_artifacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='calculator.weapons'),
        ),
    ]
